defaults:
  - trainer: default
model: "EleutherAI/pythia-160m"
log_dir: "safetyfiles"
log_wandb: false
run_name: neox-160m-3epochs
wandb_entity: "shahules786"
max_length: 512
per_digit_tokens: False
special_tokens:
  eos_token: "</s>"
  sep_token: "<sep>"
  pad_token: "<pad>"
datasets:
  - kaggle:
        split: "train"

validation_size: 0.001
